# Generated by Django 4.2.29 on 2026-05-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(default='bi-patch-check-fill', help_text='Bootstrap icon class for the certificate type', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('is_verified', models.BooleanField(default=True)),
                ('credential_url', models.URLField(blank=True, help_text='Link to verify the certificate')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('devops', 'DevOps & Infrastructure'), ('tools', 'Tools & Workflow'), ('other', 'Other')], default='backend', max_length=20)),
                ('icon', models.CharField(choices=[('bi-filetype-py', 'Python'), ('bi-server', 'Server/Django'), ('bi-lightning-charge', 'Lightning/FastAPI'), ('bi-database', 'Database'), ('bi-box', 'Box/Docker'), ('bi-git', 'Git'), ('bi-code-slash', 'Code'), ('bi-diagram-3', 'Diagram/Nginx'), ('bi-arrow-repeat', 'Repeat/Gunicorn'), ('bi-graph-up', 'Graph/React'), ('bi-ubuntu', 'Ubuntu'), ('bi-filetype-html', 'HTML'), ('bi-filetype-css', 'CSS'), ('bi-filetype-js', 'JavaScript'), ('bi-robot', 'Robot/Bot'), ('bi-cloud', 'Cloud'), ('bi-shield-check', 'Security'), ('bi-cpu', 'CPU/Processing'), ('bi-terminal', 'Terminal'), ('bi-braces', 'Braces/API'), ('bi-hdd-network', 'Network'), ('bi-layers', 'Layers')], default='bi-code-slash', help_text='Bootstrap icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
